### ISSUE TITLE
Do not transform default value

### ISSUE THREAD

**Issue by rockneurotiko** [rockneurotiko/config_tuples#19]
Currently the transform is being apply at the end after deciding to use the default value or not, and the default value shouldn't be affected by the transform.

Example:

`{:system, "INT_VALUE", default: 2, transform: {Module, :parse_int}}`

If `"INT_VALUE"` is not set, currently it will call `Module.parse_int(2)` and if you only expect strings there it can fail.

Expected behaviour: It should call the transform method only with the environment value and not with the default one.

**Comment by avillen** [comment]
I have written a proposal for this issue https://github.com/rockneurotiko/config_tuples/pull/20. Let me know if looks good for you :smile:

**Comment by rockneurotiko** [comment]
Closed with #20
